# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "4.0.2"

[[constraint]]
  name = "github.com/go-chi/cors"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-chi/jwtauth"
  version = "4.0.2"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.1"

[[constraint]]
  name = "github.com/newrelic/go-agent"
  version = "2.11.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.10.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
